### ISSUE TITLE
INFORMATION 

### ISSUE THREAD

**Issue by barto95100** [urusha/zabbix-matrix#1]
Hi,

I test your script

but I don't know how to add the room for script send notification ? 

Thank's for your help :)

**Comment by wioxjk** [comment]
It looks like it is designed to only send messages to a users - and not a room sadly

**Comment by urusha** [comment]
It's designed to send messages/calls to any type of unencrypted room. Please, see updated documentation https://github.com/urusha/zabbix-matrix/blob/master/README.md
