### ISSUE TITLE
message sent in media types but not received

### ISSUE THREAD

**Issue by monaxiko** [urusha/zabbix-matrix#2]
Hi!

I download the files into the selected directory and modify the URL and TOKEN variables according to my account. The rest of the file is identical. I try to send a message using zabbix and the output is: Media type test successful. So, I should be work fine, but not.

Can you help me with the URL. Right now, I have this one because the default doesn't work: URL   = "https://matrix.to/#"

Thanks in advance
monaxiko

**Comment by urusha** [comment]
I guess you need `https://matrix.org`
